feat: databendWriter support replace mode
alibaba/DataX pull request #1866
Opened 2023-08-02 06:50 UTC by hantmac

- support replace mode for databend

2023-08-02 07:35 UTC, dingxiaobo requested changes

2023-08-02 07:35 UTC, dingxiaobo commented on databendwriter/src/main/java/com/alibaba/datax/plugin/writer/databendwriter/util/DatabendWriterUtil.java
> +            // for databend if you want to use replace mode, the writeMode should be:  "writeMode": "replace (userid)"
`"writeMode": "replace (userid)"` 不太符合datax的写法，把这两个分开吧：

``` json
{
"writeMode": "replace"
"conflictColumn" : ["userid", "..."]
}
```

2023-08-02 07:35 UTC, dingxiaobo commented on databendwriter/src/main/java/com/alibaba/datax/plugin/writer/databendwriter/util/DatabendWriterUtil.java
> +            // for databend if you want to use replace mode, the writeMode should be:  "writeMode": "replace (userid)"
在 `DataX/databendwriter/doc/databendwriter*.md` 里也说明一下replace 怎么使用吧

2023-08-03 01:29 UTC, dingxiaobo requested changes

2023-08-03 01:29 UTC, dingxiaobo commented on databendwriter/src/main/java/com/alibaba/datax/plugin/writer/databendwriter/util/DatabendWriterUtil.java
> +                return;
看起来抛异常，让任务失败更合适

2023-08-04 08:27 UTC, hantmac commented
HI @dingxiaobo , would u like to help me review again? Thanks very much !

2023-08-09 07:27 UTC, merged